### ISSUE TITLE
A few questions

### ISSUE THREAD

**Issue by Steven2919** [tenten8401/pterodactyl-unturned#2]
Hey, not exactly an issue, I didn't know where else to contact you. 
Could you explain what you ment to do with the file entrypoint.sh and Dockerfile? (In your pterodactyl-unturned git)

I did manage to find out to install the egg ofcourse.

Thanks in advance!

**Comment by tenten8401** [comment]
the entrypoint.sh and Dockerfile are purely for building the docker container, unless you plan on modifying the egg, all you need is the JSON file to install it in the panel.

I would recommend using the GitLab version instead though as I'm not updating this GitHub repo anymore.
https://gitlab.com/tenten8401/pterodactyl-unturned

**Comment by Steven2919** [comment]
Hey, me again.

Thanks for your fast reply!

Again, the problem that I keep encountering(also with the github version) is that Pterodactyl keeps saying it is installing the server. Now I don't know exactly how long it takes but from my lame perspective it should not take any longer then 30 minutes.

That's why I was wondering where these 2 other files (entrypoint.sh and the Dockerfile) were for, since I did not do anything with them.

And I did get an e-mail from steam (since you have to enter a steamusername+password) with a verification code in it, so it is doing something.

I look forward to your reply,
Steven
